export const ADD_TO_CART = 'ADD_TO_CART';
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const REMOVE_FROM_CARD = 'REMOVE_FROM_CARD';
export const REMOVE_ALL_FROM_CARD = 'REMOVE_ALL_FROM_CARD';
export const RECEIVE_START = 'RECEIVE_START';
export const RECEIVE_ERROR = 'RECEIVE_ERROR';
export const RECEIVE_SUCCESS = 'RECEIVE_SUCCESS';
